"""
Hybrid encryption for manifest contact hints (spec v0.1 promises encrypted
hints; this module is what actually makes that true instead of aspirational).

Every trustee and beneficiary gets a SEPARATE encryption keypair from their
signing keypair. This is deliberate: Ed25519 (signing) and X25519 (key
agreement) are different curves built for different jobs, and mixing them —
converting one key type into the other — is a well-known source of subtle
cryptographic mistakes. Two keypairs per person is more bookkeeping but it's
the boring, correct choice.

Scheme (a minimal ECIES construction):
  1. Generate an ephemeral X25519 keypair for this one message.
  2. ECDH between the ephemeral private key and the recipient's public key
     produces a shared secret.
  3. HKDF-SHA256 stretches that shared secret into a 256-bit AES key.
  4. AES-256-GCM encrypts the plaintext hint with that key.
  5. Package (ephemeral public key || nonce || ciphertext) as the output.

The recipient reverses this: ECDH with their private key + the ephemeral
public key packaged alongside the ciphertext reproduces the same shared
secret, without ever needing the sender's identity key.
"""

from __future__ import annotations

import base64
import os

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric.x25519 import (
    X25519PrivateKey,
    X25519PublicKey,
)
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

_NONCE_LEN = 12
_PUBKEY_LEN = 32
_HKDF_INFO = b"dlp-contact-hint-v1"


class HintDecryptionError(ValueError):
    """Raised when a hint can't be decrypted — wrong key, corrupted data,
    or tampering. Deliberately doesn't distinguish which, so callers can't
    be used as a decryption oracle."""


def generate_encryption_keypair() -> tuple[str, str]:
    """Returns (private_key_b64, public_key_b64) for X25519 key agreement.
    Keep these separate from the Ed25519 signing keys generated by
    dlp.crypto.generate_keypair()."""
    private_key = X25519PrivateKey.generate()
    public_key = private_key.public_key()
    priv_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    pub_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return (
        "x25519:" + base64.b64encode(priv_bytes).decode(),
        "x25519:" + base64.b64encode(pub_bytes).decode(),
    )


def _strip_prefix(key_str: str, expected_prefix: str = "x25519:") -> bytes:
    if not key_str.startswith(expected_prefix):
        raise ValueError(f"expected key string prefixed with '{expected_prefix}'")
    return base64.b64decode(key_str[len(expected_prefix) :])


def encrypt_hint(plaintext: str, recipient_public_key_b64: str) -> str:
    """Encrypts a contact hint (or any short string) for one recipient.
    Returns a single base64 blob safe to store directly in a manifest's
    contact_hint field."""
    recipient_pub_bytes = _strip_prefix(recipient_public_key_b64)
    recipient_pub = X25519PublicKey.from_public_bytes(recipient_pub_bytes)

    ephemeral_priv = X25519PrivateKey.generate()
    ephemeral_pub_bytes = ephemeral_priv.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )

    shared_secret = ephemeral_priv.exchange(recipient_pub)
    aes_key = HKDF(algorithm=hashes.SHA256(), length=32, salt=None, info=_HKDF_INFO).derive(
        shared_secret
    )

    nonce = os.urandom(_NONCE_LEN)
    ciphertext = AESGCM(aes_key).encrypt(nonce, plaintext.encode("utf-8"), None)

    blob = ephemeral_pub_bytes + nonce + ciphertext
    return "dlp-enc:" + base64.b64encode(blob).decode()


def decrypt_hint(encrypted_b64: str, recipient_private_key_b64: str) -> str:
    """Reverses encrypt_hint. Raises HintDecryptionError on any failure —
    wrong key, corrupted blob, or tampered ciphertext all look the same
    from the outside, which is the correct behavior for authenticated
    encryption (AES-GCM already prevents tampering; we just don't leak
    *why* decryption failed)."""
    if not encrypted_b64.startswith("dlp-enc:"):
        raise HintDecryptionError("not a recognized encrypted-hint blob")

    try:
        blob = base64.b64decode(encrypted_b64[len("dlp-enc:") :])
        ephemeral_pub_bytes = blob[:_PUBKEY_LEN]
        nonce = blob[_PUBKEY_LEN : _PUBKEY_LEN + _NONCE_LEN]
        ciphertext = blob[_PUBKEY_LEN + _NONCE_LEN :]

        recipient_priv_bytes = _strip_prefix(recipient_private_key_b64)
        recipient_priv = X25519PrivateKey.from_private_bytes(recipient_priv_bytes)
        ephemeral_pub = X25519PublicKey.from_public_bytes(ephemeral_pub_bytes)

        shared_secret = recipient_priv.exchange(ephemeral_pub)
        aes_key = HKDF(algorithm=hashes.SHA256(), length=32, salt=None, info=_HKDF_INFO).derive(
            shared_secret
        )

        plaintext = AESGCM(aes_key).decrypt(nonce, ciphertext, None)
        return plaintext.decode("utf-8")
    except (InvalidTag, ValueError, IndexError) as e:
        raise HintDecryptionError("could not decrypt hint — wrong key or corrupted data") from e


def is_encrypted_hint(value: str) -> bool:
    """Cheap check for whether a contact_hint field is already encrypted,
    used by ManifestBuilder to avoid double-encrypting."""
    return isinstance(value, str) and value.startswith("dlp-enc:")
